quarkus:
  http:
    port: 10000
  log:
    category:
      "com.crionuke.omgameserver":
        level: TRACE
        min-level: TRACE
omgameserver:
  websocket:
    bufferSize: 128
  runtime:
    bufferSize: 1024
    jsonService:
      poolSize: 2

"%dev":
  omgameserver:
    runtime:
      bootstrapService:
        initialWorkers:
          - rootDirectory: "examples/echoServer"
            mainScript: "server/main.lua"
            tickEveryMillis: 1000
            address:
              tenant: "crionuke"
              game: "echoserver"
              worker: "main"
          - rootDirectory: "examples/hubServer"
            mainScript: "server/main.lua"
            tickEveryMillis: 1000
            address:
              tenant: "crionuke"
              game: "hubserver"
              worker: "main"
