quarkus:
  http:
    port: 10000
  log:
    category:
      "com.crionuke.omgameserver":
        level: DEBUG
omgameserver:
  websocket:
    bufferSize: 128
  runtime:
    bufferSize: 1024
    json:
      poolSize: 2
    bootstrap:
      - rootDirectory: "examples/echoServer"
        mainScript: "server/main.lua"
        tickEveryMillis: 1000
        address:
          tenant: "crionuke"
          game: "echoserver"
          worker: "main"
      - rootDirectory: "examples/hubServer"
        mainScript: "server/main.lua"
        tickEveryMillis: 1000
        address:
          tenant: "crionuke"
          game: "hubserver"
          worker: "main"