quarkus:
  http:
    port: 10000
  log:
    category:
      "com.crionuke.omgameserver":
        level: DEBUG
omgameserver:
  websocket:
    bufferSize: 128
  runtime:
    bufferSize: 1024
    json:
    bootstrap:
      - script: "examples/echoServer/server/server.lua"
        tickEveryMillis: 1000
        address:
          tenant: "crionuke"
          game: "echoserver"
          worker: "main"
      - script: "examples/hubServer/server/server.lua"
        tickEveryMillis: 5000
        address:
          tenant: "crionuke"
          game: "hubserver"
          worker: "main"