quarkus:
  http:
    port: 10000
omgameserver:
  websocket:
    bufferSize: 128
  runtime:
    bufferSize: 1024
    bootstrap:
      script: "examples/franticSky/server/server.lua"
      address:
        tenant: "crionuke"
        game: "franticSky"
        worker: "lobby"