quarkus:
  http:
    port: 20000
  log:
    category:
      "com.crionuke.omgameserver":
        level: DEBUG
integrationTests:
  echoServer:
    timeoutInMillis: 1000
    webSocketEndpoint: "http://localhost:10000/omgameserver/v1/ws/crionuke/echoserver/main"